export enum NotificationType {
  SEND_TEXT = 'SEND_TEXT',
  SEND_IMAGE = 'SEND_IMAGE',
  SEND_DOCUMENT = 'SEND_DOCUMENT',
  BUTTON_LIST = 'BUTTON_LIST',
  BUTTON_ACTIONS = 'BUTTON_ACTIONS',
  BUTTON_OTP = 'BUTTON_OTP',
  BUTTON_PIX = 'BUTTON_PIX',
}
